export const PHONE_STEP = 'PHONE_STEP';

export const PHONE_STEP_STATE_INIT = 'PHONE_STEP_STATE_INIT';
export const PHONE_STEP_STATE_UNKNOWN = 'PHONE_STEP_STATE_UNKNOWN';
export const PHONE_STEP_STATE_ERROR = 'PHONE_STEP_STATE_ERROR';
export const PHONE_STEP_STATE_SUCCESS = 'PHONE_STEP_STATE_SUCCESS';

export const CODE_STEP = 'CODE_STEP';

export const CODE_STEP_STATE_INIT = 'CODE_STEP_STATE_INIT';
export const CODE_STEP_STATE_UNKNOWN = 'CODE_STEP_STATE_UNKNOWN';
export const CODE_STEP_STATE_ERROR = 'CODE_STEP_STATE_ERROR';
export const CODE_STEP_STATE_SUCCESS = 'CODE_STEP_STATE_SUCCESS';

export const USER_CONTACTS_STEP = 'USER_CONTACTS_STEP';

export const USER_CONTACTS_STEP_STATE_INIT = 'USER_CONTACTS_STEP_STATE_INIT';
export const USER_CONTACTS_STEP_STATE_UNKNOWN = 'USER_CONTACTS_STEP_STATE_UNKNOWN';
export const USER_CONTACTS_STEP_STATE_ERROR = 'USER_CONTACTS_STEP_STATE_ERROR';
export const USER_CONTACTS_STEP_STATE_SUCCESS = 'USER_CONTACTS_STEP_STATE_SUCCESS';

export const COMPANY_STEP = 'COMPANY_STEP';

export const COMPANY_STEP_STATE_INIT = 'COMPANY_STEP_STATE_INIT';
export const COMPANY_STEP_STATE_UNKNOWN = 'COMPANY_STEP_STATE_UNKNOWN';
export const COMPANY_STEP_STATE_ERROR = 'COMPANY_STEP_STATE_ERROR';
export const COMPANY_STEP_STATE_SUCCESS = 'COMPANY_STEP_STATE_SUCCESS';

export const ACTIVATE_STEP = 'ACTIVATE_STEP';

export const ACTIVATE_STEP_STATE_INIT = 'ACTIVATE_STEP_STATE_INIT';
export const ACTIVATE_STEP_STATE_UNKNOWN = 'ACTIVATE_STEP_STATE_UNKNOWN';
export const ACTIVATE_STEP_STATE_ERROR = 'ACTIVATE_STEP_STATE_ERROR';
export const ACTIVATE_STEP_STATE_SUCCESS = 'ACTIVATE_STEP_STATE_SUCCESS';

export const XERO_STEP = 'XERO_STEP';

export const XERO_STEP_STATE_INIT = 'XERO_STEP_STATE_INIT';
export const XERO_STEP_STATE_UNKNOWN = 'XERO_STEP_STATE_UNKNOWN';
export const XERO_STEP_STATE_ERROR = 'XERO_STEP_STATE_ERROR';
export const XERO_STEP_STATE_SUCCESS = 'XERO_STEP_STATE_SUCCESS';

export const INTRO_STEP = 'INTRO_STEP';

export const INTRO_STEP_STATE_INIT = 'INTRO_STEP_STATE_INIT';
export const INTRO_STEP_STATE_UNKNOWN = 'INTRO_STEP_STATE_UNKNOWN';
export const INTRO_STEP_STATE_ERROR = 'INTRO_STEP_STATE_ERROR';
export const INTRO_STEP_STATE_SUCCESS = 'INTRO_STEP_STATE_SUCCESS';

export const INVOICE_DATE_STEP = 'INVOICE_DATE_STEP';

export const INVOICE_DATE_STEP_STATE_INIT = 'INVOICE_DATE_STEP_STATE_INIT';
export const INVOICE_DATE_STEP_STATE_UNKNOWN = 'INVOICE_DATE_STEP_STATE_UNKNOWN';
export const INVOICE_DATE_STEP_STATE_ERROR = 'INVOICE_DATE_STEP_STATE_ERROR';
export const INVOICE_DATE_STEP_STATE_SUCCESS = 'INVOICE_DATE_STEP_STATE_SUCCESS';

export const MAPPINGS_STEP = 'MAPPINGS_STEP';

export const SUCCESS_STEP = 'SUCCESS_STEP';
export const SUCCESS_STEP_STATE_INIT = 'SUCCESS_STEP_STATE_INIT';

export const SHOPIFY_MACHINE = 'shopify';

export const SUCCESS_EVENT = 'SUCCESS_EVENT';
export const ERROR_EVENT = 'ERROR_EVENT';

export const initialContext = {
  phone: '',
  verificationToken: '',
  token: '',
  user: null,
  companies: [],
  conversations: [],
  store: null,
  mappings: [],
  contracts: [],
  activeCompanyId: null,
  error: null,
};
